
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author htmjs
 */
public class TehtavanVaraus extends javax.swing.JFrame {

    /**
     * Creates new form TehtavanVaraus
     */
    public TehtavanVaraus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNayta = new javax.swing.JButton();
        btnPoista = new javax.swing.JButton();
        btnLopeta = new javax.swing.JButton();
        btnAloita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "Start", "Stop", "Description", "Place", "Reserved"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Varatut tehtävät");

        btnNayta.setText("Näytä");
        btnNayta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaytaActionPerformed(evt);
            }
        });

        btnPoista.setText("Poista tehtävä");
        btnPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoistaActionPerformed(evt);
            }
        });

        btnLopeta.setText("Lopeta tehtävä");
        btnLopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopetaActionPerformed(evt);
            }
        });

        btnAloita.setText("Aloita tehtävä");
        btnAloita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAloitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAloita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPoista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNayta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnLopeta)))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAloita, btnLopeta, btnNayta, btnPoista});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNayta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLopeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAloita)
                    .addComponent(btnPoista))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAloita, btnLopeta, btnNayta, btnPoista});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaytaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaytaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController pmc = new ProjectManagementController();
        MyTableModel3 model = new MyTableModel3(pmc.getReserved());
        
        jTable1.setModel(model);
    }//GEN-LAST:event_btnNaytaActionPerformed

    private void btnPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoistaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController p = new ProjectManagementController();
        int row = jTable1.getSelectedRow();
        MyTableModel3 model = (MyTableModel3)jTable1.getModel();
        
        String valittu = model.getValueAt(row, 3).toString();
        
        if (row >= 0) {
            p.DeleteReserved(valittu);
        }
        
        
    }//GEN-LAST:event_btnPoistaActionPerformed

    private void btnLopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopetaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController p = new ProjectManagementController();
        int row = jTable1.getSelectedRow();
        MyTableModel3 model = (MyTableModel3)jTable1.getModel();
        
        String valittu = model.getValueAt(row, 3).toString();
        
        if (row >= 0) {
            p.Stop(valittu);
        }
    }//GEN-LAST:event_btnLopetaActionPerformed

    private void btnAloitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAloitaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController p = new ProjectManagementController();
        int row = jTable1.getSelectedRow();
        MyTableModel3 model = (MyTableModel3)jTable1.getModel();
        
        String valittu = model.getValueAt(row, 3).toString();
        
        if (row >= 0) {
            p.Start(valittu);
        }
    }//GEN-LAST:event_btnAloitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TehtavanVaraus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TehtavanVaraus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TehtavanVaraus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TehtavanVaraus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TehtavanVaraus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAloita;
    private javax.swing.JButton btnLopeta;
    private javax.swing.JButton btnNayta;
    private javax.swing.JButton btnPoista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
