/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s698338
 */
public class Tehtävät extends javax.swing.JFrame {
    protected final User kayttaja;
    
    
    /**
     * Creates new form Tehtävät
     */
    public Tehtävät(User u) {
        kayttaja = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNayta = new javax.swing.JButton();
        btnLuo = new javax.swing.JButton();
        btnVaraa = new javax.swing.JButton();
        btnNaytaVaratut = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "Start", "Stop", "Description", "Place", "Reserved"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");
        jTable1.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tehtävät");

        btnNayta.setText("Näytä");
        btnNayta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaytaActionPerformed(evt);
            }
        });

        btnLuo.setText("Luo uusi tehtävä");
        btnLuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuoActionPerformed(evt);
            }
        });

        btnVaraa.setText("Varaa Tehtävä");
        btnVaraa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaraaActionPerformed(evt);
            }
        });

        btnNaytaVaratut.setText("Varatut tehtävät");
        btnNaytaVaratut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaytaVaratutActionPerformed(evt);
            }
        });

        btnReserve.setText("Varaa");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNayta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNaytaVaratut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVaraa)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnReserve)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLuo, btnNayta, btnNaytaVaratut, btnReserve, btnVaraa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNayta, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnLuo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaytaVaratut)
                    .addComponent(btnVaraa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReserve)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLuo, btnNayta, btnNaytaVaratut, btnReserve, btnVaraa});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaytaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaytaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController pmc = new ProjectManagementController();
        MyTableModel2 model = new MyTableModel2(pmc.getTasks());
        
        jTable1.setModel(model);
        
    }//GEN-LAST:event_btnNaytaActionPerformed

    private void btnLuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuoActionPerformed
        // TODO add your handling code here:
        new TehtavanLuonti().setVisible(true);
    }//GEN-LAST:event_btnLuoActionPerformed

    private void btnVaraaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaraaActionPerformed
        // TODO add your handling code here:
        ProjectManagementController p = new ProjectManagementController();
        int row = jTable1.getSelectedRow();
        MyTableModel2 model = (MyTableModel2)jTable1.getModel();
        
        //int user_id = (int) jTable1.getModel().getValueAt(row, 0);
       
        String valittu = model.getValueAt(row, 3).toString();
        
        p.moveTask(valittu);
        //p.updateId(user_id, kayttaja.getId());
        //int user_id = model.getValueAt(row, 3).hashCode();
        //int id = model.getValueAt(row, 3).hashCode();
        
        /*
        if (row > -1) {
            p.moveTask(valittu);
            p.updateId(user_id, valittu);
        }
        */
    }//GEN-LAST:event_btnVaraaActionPerformed

    private void btnNaytaVaratutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaytaVaratutActionPerformed
        // TODO add your handling code here:
        new TehtavanVaraus().setVisible(true);
    }//GEN-LAST:event_btnNaytaVaratutActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
        ProjectManagementController p = new ProjectManagementController();
        int row = jTable1.getSelectedRow();
        MyTableModel2 model = (MyTableModel2)jTable1.getModel();
        
        int user_id = (int) jTable1.getModel().getValueAt(row, 0);
        
        p.updateId(user_id, kayttaja.getId());
    }//GEN-LAST:event_btnReserveActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tehtävät.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tehtävät.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tehtävät.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tehtävät.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User u = null;
                new Tehtävät(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuo;
    private javax.swing.JButton btnNayta;
    private javax.swing.JButton btnNaytaVaratut;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnVaraa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
